<a href="https://colab.research.google.com/github/Himanshu-Meshram/UM-Python/blob/main/DAY7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy Array Slicing**


*   Slicing in Python means taking elelments from one given index to another given index.

*   We pass slice instead of index like this : [start:end].

*   We can also define the step, like this: [start:end:step].







In [172]:
import numpy as np

arr = np.array ([1,2,3,4,5,6,7,8,9,10,11])                                                        # Accessing 1D array

# print(arr)
# print(arr[2])
# print(arr[1:2])                                                                                 # [start:end]
# print(arr[1:5])
# print(arr[8:10])
# print(arr[5:8])
# print(arr[3:8])

# print(arr[:5])
# print(arr[1:11:2])
# print(arr[:11:3])
# print(arr[::2])
# print(arr[::5])
# print(arr[2::])
# print(arr[4::])
# print(arr[7::])


# a1 = np.array([[1,2,3,4,5,6],[7,8,9,0,1,2],[3,4,5,6,7,8],[9,0,1,2,3,4]])                         # was trying to create a 4X4 martix
# print(a1)
# print(a1[1,1:4])                                                                                 #
# print(a1[0:4,1])
# print(a1[0:3,1])
# print(a1[0:3,2])



#



# arr1 = np.array([[1,2,3,4,5,6],[7,8,9,0,1,2]])                                                     # Accessing 2D Array

# print(arr1)
# print(arr1[1,2:4])                                                                               # Slicing with columns
# print(arr1[0,::2])                                                                               # [row, row:column:step]
# print(arr1[1,1:4])
# print(arr1[1,2:3])
# print(arr1[1,0::2])

# print(arr1[0:2,4])                                                                               # Slicing with row
# print(arr1[0:3,4])                                                                               # [row:column:step ,elements]
# print(arr1[:3,4])
# print(arr1[::1,3])
# print(arr1[::2,4])

# print(arr1[0:2,0:2])                                                                              # Slicing with both rows and columns
# print(arr1[0:2,1:3])
## print(arr1[0:2,1:5])  ?
## print(arr1[0:1,1:4])  ?



#



arr2 = np.array([[[1,2,3],[1,2,3],[1,2,3]],                                                    # Slicing 3D Array
                [[1,2,3],[1,2,3],[1,3,2]],
                [[1,2,3],[1,2,3],[1,2,3]]])
print(arr2)
# print(arr2.shape)
# print(arr2[:2,1:,:2])                                                                                # [matrix:row:column]
                                                                ## print (arr2[:2{matrix using},2:[rows using in those matrix],:3[columns using in that matrix]])
# print(arr2[:3,:3,1:2])
# print(arr2[:3,2:3,1:2])
# print(arr2[1:2,1:2,2:3])
# print(arr2[1:2,2:3,1:2])



[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 3 2]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]]
[[[3]]]


# **View vs Copy**



*   Copy is a new array, and the View is just a view of the original array.
*   Any changes made to the ***copy*** will not affect original array.
*   Any changes made to the ***view*** will afect the original array.



In [192]:
arr = np.array([1,2,3,4,5,9,5,7])

# copy = arr.copy()                                                                                 # Copy Method
# copy[0] = 22
# print(copy)

# copy = arr.copy()                                                                                 # Modifing new array
# copy[2] = 44
# print(copy)

# print(arr)                                                                                        # Doesnt effect the original one



#



arr1 = np.array([1,2,3,4,5,9,5,7])

# view = arr1.view()                                                                                   # View Method
# view[0] = 100                                                                                        # Modifing new array
# print(view)
# print (arr1)                                                                                         # Affecting original array





















[100   2   3   4   5   9   5   7]
[100   2   3   4   5   9   5   7]
