<a href="https://colab.research.google.com/github/Himanshu-Meshram/UM-Python/blob/main/%E2%AD%90_DAY7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy Array Slicing**


*   Slicing in Python means taking elelments from one given index to another given index.

*   We pass slice instead of index like this : [start:end].

*   We can also define the step, like this: [start:end:step].







In [ ]:
import numpy as np

arr = np.array ([1,2,3,4,5,6,7,8,9,10,11])                                                        # Accessing 1D array

# print(arr)
# print(arr[2])
# print(arr[1:2])                                                                                 # [start:end]
# print(arr[1:5])
# print(arr[8:10])
# print(arr[5:8])
# print(arr[3:8])

# print(arr[:5])
# print(arr[1:11:2])
# print(arr[:11:3])
# print(arr[::2])
# print(arr[::5])
# print(arr[2::])
# print(arr[4::])
# print(arr[7::])


# a1 = np.array([[1,2,3,4,5,6],[7,8,9,0,1,2],[3,4,5,6,7,8],[9,0,1,2,3,4]])                         # was trying to create a 4X4 martix
# print(a1)
# print(a1[1,1:4])                                                                                 #
# print(a1[0:4,1])
# print(a1[0:3,1])
# print(a1[0:3,2])



#



# arr1 = np.array([[1,2,3,4,5,6],[7,8,9,0,1,2]])                                                     # Accessing 2D Array

# print(arr1)
# print(arr1[1,2:4])                                                                               # Slicing with columns
# print(arr1[0,::2])                                                                               # [row, row:column:step]
# print(arr1[1,1:4])
# print(arr1[1,2:3])
# print(arr1[1,0::2])

# print(arr1[0:2,4])                                                                               # Slicing with row
# print(arr1[0:3,4])                                                                               # [row:column:step ,elements]
# print(arr1[:3,4])
# print(arr1[::1,3])
# print(arr1[::2,4])

# print(arr1[0:2,0:2])                                                                              # Slicing with both rows and columns
# print(arr1[0:2,1:3])
## print(arr1[0:2,1:5])  ?
## print(arr1[0:1,1:4])  ?



#



arr2 = np.array([[[1,2,3],[1,2,3],[1,2,3]],                                                    # Slicing 3D Array
                [[1,2,3],[1,2,3],[1,3,2]],
                [[1,2,3],[1,2,3],[1,2,3]]])
print(arr2)
# print(arr2.shape)
# print(arr2[:2,1:,:2])                                                                                # [matrix:row:column]
                                                                ## print (arr2[:2{matrix using},2:[rows using in those matrix],:3[columns using in that matrix]])
# print(arr2[:3,:3,1:2])
# print(arr2[:3,2:3,1:2])
# print(arr2[1:2,1:2,2:3])
# print(arr2[1:2,2:3,1:2])



[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 3 2]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]]
[[[3]]]


# **View vs Copy**



*   Copy is a new array, and the View is just a view of the original array.
*   Any changes made to the ***copy*** will not affect original array.
*   Any changes made to the ***view*** will afect the original array.



In [ ]:
arr = np.array([1,2,3,4,5,9,5,7])

# copy = arr.copy()                                                                                 # Copy Method
# copy[0] = 22
# print(copy)

# copy = arr.copy()                                                                                 # Modifing new array
# copy[2] = 44
# print(copy)

# print(arr)                                                                                        # Doesnt effect the original one



#



arr1 = np.array([1,2,3,4,5,9,5,7])

# view = arr1.view()                                                                                   # View Method
# view[0] = 100                                                                                        # Modifing new array
# print(view)
# print (arr1)                                                                                         # Affecting original array





















[100   2   3   4   5   9   5   7]
[100   2   3   4   5   9   5   7]


# **Numpy Major and Minor Operations**

* Append, Insert and Delete Operations.







In [90]:
import numpy as np                                                              # APPEND METHOD

# a = np.array([[1,2,3],[4,5,6]])
# print(a)


# np.append(a,[7,8,9])
# print(a)
# np.append(a,[6,5,4])                                                                         # Not assigned where to add


# a1 = np.append(a,[7,8,9])                                                                    # saving 1st append and re-appending
# print(a1)
# np.append(a1,[6,5,4])


#

#ROW                                                                                           # assigning where to add {0 = row ; 1 = column}

# np.append(a,[[7,5,3]],axis=0)
# np.append(a,[[11,22,33]],axis=0)                                                             # syntax (array,[[a,b,c]],axis=0)
# np.append(a,[[66,55,44]],axis=0)                                                             # values = 'row size'

# Column

# np.append(a,[[9],[7]],axis=1)                                                                # syntax (array,[[a],[b]],axis=1)
# np.append(a,[[44],[55]],axis=1)
# np.append(a,[[88],[990]],axis=1)                                                             # values = 'column size'



###-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------



#                                                                               # INSERT METHOD



# a1 = np.array([[1,2],[4,5],[7,8]])                                                           # assigning where to add {0 = row ; 1 = column}
# print(a1)

#ROW

# np.insert(a,2,[11,22])                                                                       # syntax (array, row position, [values],axis=0)
# np.insert(a,1,[44,55,66],axis=0)                                                             # values = no. of elements in the column
# np.insert(a,0,[69,69,69],axis=0)

# Column

# np.insert(a1,1,[56,45,84],axis=1)                                                            # syntax (array, column position, [values], axis = 1)
# np.insert(a1,0,[00,00,00],axis=1)
# np. insert(a1,2,[111,222,333],axis=1)



###-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------




#                                                                               # DELETE METHOD


# a2 = np.array([[1,2,3,44],[4,5,6,55],[7,8,9,66]])
# print(a2)
# np.ndim(a2)                                                                                    # 2D



# INDEX

# np.delete(a2,5)                                                                                # syntax (array, element position in the martix)
# np.delete(a2,7)
# np.delete(a2,9)

# ROW

# np.delete(a2,1,axis=0)                                                                         # syntax (array, position of the row, axis = 0)
# np.delete(a2,2,axis=0)

# COLUMN

# np.delete(a2,0,axis = 1)                                                                       # syntax (array, position of the column, axis = 1)
# np.delete(a2,3,axis = 1)



###-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------



[[ 1  2  3 44]
 [ 4  5  6 55]
 [ 7  8  9 66]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# **Hstack vs Vstack**



*   Hstack is used to join two arrays Horizontally
*   Vstack is used to join two arrays Vertically.



In [104]:

a = np.array([1,2,3,4])                                                                            # Accessing arrays
b = np.array([5,6,7,8])
print(a,b)
# print(np.ndim(a),np.ndim(b))                                                                       # dimension of the array


                                                                                # Performing Hstack

# ab = np.hstack((a,b))                                                                              # syntax {np.hstack((array1,array2))}
# print(ab)

                                                                                # Performing Vstack


ab = np.vstack((a,b))                                                                                # syntax {np.vstack((array1,array2))}
print(ab)





[1 2 3 4] [5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


# **Numpy Concatenation**



*   It is used for joining two or more arrays of the same shape along a specified axis.


Axis = 0, Adding new rows.

Axis = 1, Adding new columns.



In [122]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

c=np.array([[9,8],[7,6]])
d=np.array([[5,4],[3,2]])
# print(a,b,c,d)


# ab = np.concatenate((a,b),axis=0)                                                                # syntax {np.concatenate((array1,array2),axis=0)}
# print(ab)

# cd = np.concatenate((c,d),axis=1)                                                                # syntax {np.concatenate((array1,array2),axis=1)}
# print(cd)


[[9 8 5 4]
 [7 6 3 2]]
