<a href="https://colab.research.google.com/github/Himanshu-Meshram/UM-Python/blob/main/%E2%AD%90DAY6_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy Array Dimensions**

Provides


1.  An array object of arbitrary homogeneous items

2.  Fast mathematical operations over arrays

3.  Linear Algebra, Fourier Transforms, Random Number Generation.




*  *   1D Array
*  *   2D Array
*  *   3D Array


In [ ]:
import numpy as np                                                                            # importing Numpy Library

# A = np.array(5)                                                                             # Scalar Method

# print(A)

# np.ndim(A)                                                                                  # Dimension Statement


One = np.array([1,2,3,5,6])
Two = np.array([[5,8,4,6,9],[4,5,6,9,6]])
Three = np.array([[[1,2,4,5,6],[4,6,8,4,5]],[[1,4,5,2,5],[8,9,5,4,6]]])

# print(One)
# print(Two)
# print(Three)

# np.ndim(One)
# np.ndim(Two)
# np.ndim(Three)





[[[1 2 4 5 6]
  [4 6 8 4 5]]

 [[1 4 5 2 5]
  [8 9 5 4 6]]]


# **List vs Numpy Array**


*   **Numpy Array -**
    * Allows Similar Datatypes.
    * Allows Mathematical Operations.
    * Array are faster then lists.
    * Array consumes less memory.

*   **List -**
    * Different Datatypes.
    * Does not allows Mathematical Operations.



In [ ]:
# List1 = [1,3.2,'apple']                                                                         # Different - Datatypes
# arr = np.array([1,5,4,3,2])                                                                     # Similar - Datatypes

# print(List1)
# print(arr)



#



# arr = np.array([1,2,4.3,'apple'])                                                               # type conversion (converted num & float in string)
# print(arr)



#



# arr = np.array([1,5,9,8,7,3])                                                                   # Allows Mathematical Operations
# List1 = [1,4,5,2,6,8,9]
# #

# print(arr/2)

# # print(List1/2)                                                                                # LIST Does not allows Mathematical Operations.




[0.5 2.5 4.5 4.  3.5 1.5]


# **Array Re-shaping**



*   Reshaping means changing the shape of an array.
*   reshape(row,column) - *1D to 2D*
*   reshape(row,depth,column) - *1D to 3D*



In [ ]:

# 1D into 2D


# arr = np.array ([1,2,3,4,5,6,7,8,9,0])                                                         # 1D Array


# arr1 = arr.reshape(5,2)                                                                        # reshape(row,column)
# print(arr1)

# arr2 = arr.reshape(2,5)
# print(arr2)




# 1D to 3D Array


# arr = np.array ([1,2,3,5,4,6,7,8,9,0,88,99])
# arrnew = arr.reshape(2,3,2)                                                                       # reshape(row,depth,column)
# print(arrnew)
#



[[[ 1  2]
  [ 3  5]
  [ 4  6]]

 [[ 7  8]
  [ 9  0]
  [88 99]]]


# **Array Indexing**



*   Array Indexing is the same as accessing an array element.
*   You can access an array element by referring to its index number.



In [ ]:
# arr = np.array([1,2,3,4,5,6])                                                                    # Accessing 1D Array
# print(arr)

# print(arr[1])
# print(arr[3])


#


# print(arr[2]+arr[3])                                                                             # Addition of two Elements
# print(arr[3]+arr[5])
# print(arr[5]*arr[2])                                                                             # Multiplication of Elements
# print(arr[4]/arr[1])                                                                             # Division of Elements
# print(arr[2]*arr[5]-arr[4])                                                                      # Multiple actions on elements



#



# arr1 = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]])                                                      # Accessing 2D Array
# print(arr1)

# print(arr1[0,1])                                                                                    # 1st Row and 2nd Element
# print(arr1[1,5])                                                                                    # arr([row,column])
# print(arr1[1,4])


#


arr2 = np.array([[[1,2,3,4,5,6],[1,2,3,5,9,7]],[[4,5,6,1,2,9],[7,5,9,4,3,2]]])                         # Accessing 3D Array
print(arr2)

# print(arr2[1,1,1])                                                                                     # 2nd Matrix, 2nd Row, 2nd Column
# print(arr2[1,0,3])                                                                                     # 2nd Matrix, 1st Row, 4th Column
# print(arr2[1,1,0])                                                                                     # 2nd Matrix, 1st Row, 1st Column



#





[[[1 2 3 4 5 6]
  [1 2 3 5 9 7]]

 [[4 5 6 1 2 9]
  [7 5 9 4 3 2]]]
5
1
7
